//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom_cnpm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string SoHD { get; set; }
        public string MaKH { get; set; }
        public string MaNVDuyet { get; set; }
        public string MaNVGiaoHang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string TinhTrang { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
